#!/usr/bin/env bash
set -euo pipefail

_err() {
  _echoerr "err: $@"
  exit 1
}

_echoerr() {
  1>&2 echo "$@"
}

subcommand=${1:-}
case $subcommand in
  kinds)
    kinds=""
    for kind in $(kubectl api-resources --verbs=list,delete -o name); do
      case $kind in
        namespaces)
          continue
        ;;
        nodes|events|events.events.k8s.io)
          continue
        ;;
      esac
      kinds="${kinds}${kind} "
    done

    echo "$kinds"
  ;;
  merge)
    base=$2
    branch=${3:-.}

    cd "$base"
    prefix=$(pwd)
    leafs=$(find $branch -type d | sort -r | awk 'a!~"^"$0{a=$0;print}')
    if [ "$leafs" = "" ]; then
      leafs="."
    fi

    yamls=""
    for leaf in $leafs; do
      # find leaf directories and walk backwards
      for resource in $(find $leaf -type f); do
        name=$(basename $resource)
        kind=${name%.*}
        files=""

        cd $leaf
        while true; do
          current=$(pwd)

          path=${current#"${prefix}"}
          for f in $(find * -maxdepth 0 -type f -name "*$kind*"); do
            files="$files ${prefix}${path}/${f}"
          done

          [ "$current" = "$prefix" ] && break

          cd ..
        done
        _echoerr "merge:${files}"
        yq -M ea '. as $item ireduce ({}; . *+ $item )' $files
      done
    done
  ;;
  eval)
    lines=""
    IFS=''
    while read line; do
      lines="${lines}${line}
"
    done
    IFS=' '

    echo "$lines" | envsubst
  ;;
  apply)
    timestamp=$(date +%Y-%m-%d-%H-%M-%S)
    prune=no
    labels=""
    opts=${@:2}
    for opt in $opts; do
      case $opt in
        --label=*)
          label=${opt#*=}
          labels="$labels $label"
          shift
        ;;
        --prune)
          prune=yes
          shift
        ;;
      esac
    done
    namespace=$2
    name=$3
    labels=" \
      ${labels} \
      app.kubernetes.io/managed-by=kung \
      kung/namespace=$namespace \
      kung/name=$name \
      kung/at=$timestamp \
    "

    manifest=""
    IFS=''
    while read line; do
      manifest="$manifest
$line"
    done
    IFS=' '

    while true; do
      >/dev/null kubectl label "namespace/$namespace" --overwrite $labels && break
      kubectl create namespace "$namespace"
    done

    printf "$manifest" | tee /dev/stderr | kubectl apply -n "$namespace" -f -
    printf "$manifest" | kubectl label -n "$namespace" --overwrite $labels -f -

    if [ "$prune" = "yes" ]; then
      for kind in $0 kinds; do
        _echoerr "delete $kind"
        kubectl delete "$kind" \
          --all-namespaces \
          -l app.kubernetes.io/managed-by=kung,kung/namespace=$namespace,kung/name=$name,kung/at!=$timestamp
      done
    fi
  ;;
  *)
    _err "?"
  ;;
esac